backend:
  name: git-gateway
  branch: main

# 当使用 GitHub 时，使用如下配置：
# name: github
# repo: your-username/your-repo
# branch: main

media_folder: "source/images/posts"
public_folder: "/images/posts"

collections:
  - name: "posts"
    label: "文章"
    folder: "source/_posts"
    create: true
    slug: "{{slug}}"
    preview_path: "{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss", default: now}
      - {label: "作者", name: "author", widget: "string", default: "XIAOYU"}
      - {label: "封面图片", name: "cover", widget: "image", required: false}
      - {label: "标签", name: "tags", widget: "list", required: false}
      - {label: "分类", name: "categories", widget: "list", required: false}
      - {label: "摘要", name: "excerpt", widget: "text", required: false}
      - {label: "正文", name: "body", widget: "markdown"}
      - label: "置顶"
        name: "sticky"
        widget: "number"
        required: false
        value_type: "int"
        min: 0
        max: 100
        step: 1
        default: 0

  - name: "pages"
    label: "页面"
    folder: "source"
    create: false
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "内容", name: "body", widget: "markdown"}
