backend:
  name: github
  repo: xiaoyu200126/xiaoyu-blog
  branch: main

media_folder: "public/images/posts"
public_folder: "/images/posts"

site_url: https://xiaoyu-blog.cn
display_url: https://xiaoyu-blog.cn

collections:
  - name: "posts"
    label: "文章"
    folder: "public"
    create: true
    slug: "{{slug}}"
    extension: html
    format: "html"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "日期", name: "date", widget: "datetime"}
      - {label: "作者", name: "author", widget: "string", default: "XIAOYU"}
      - {label: "标签", name: "tags", widget: "list", required: false}
      - {label: "分类", name: "categories", widget: "list", required: false}
      - {label: "摘要", name: "excerpt", widget: "text", required: false}
      - {label: "正文", name: "body", widget: "markdown"}
